services:
  reproxy:
    image: umputun/reproxy:master
    container_name: reproxy
    hostname: reproxy
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DOCKER_ENABLED=true
      - LOGGER_ENABLED=true
      - LOGGER_STDOUT=true      
      - DOCKER_AUTO=true
      - DEBUG=true
      - MAX_SIZE=15M
      - SSL_TYPE=auto
      - SSL_ACME_FQDN=lk-test.sensetower.io
      - HEADER=
          X-Frame-Options:SAMEORIGIN,
          X-XSS-Protection:1; mode=block;,
          Content-Security-Policy:default-src 'self' *.sensetower.io; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com; script-src 'self' 'unsafe-inline' https://kit.fontawesome.com https://cdn.jsdelivr.net https://buttons.github.io https://cdnjs.cloudflare.com;
  client-web:
    container_name: client-web
    hostname: client-web
    image: "cr.yandex/crplei8g9hfd1jrmpva5/sc.st.client.web.test 2022-11-24.0"
    ports:
      - "7775:80"
    restart: always
    labels:
      reproxy.route: '^/(.*)'
      reproxy.dest: '/@1'
      reproxy.port: '7775'